### ISSUE TITLE
Deploy multiple RSSDs omnibus web UIs container

### ISSUE THREAD

**Issue by shah** [surveilr/www.surveilr.com#125]
Introduce a Dockerfile that builds, configures, and serves multiple RSSD (SQLite) databases generated by the `surveilr` CLI. The container should include dynamic Traefik proxying, allowing access to each RSSD via unique endpoints, with flexibility for deployment paths. 

<mark>A draft version of the Dockerfile is located at [`support/deploy/omnibus-rssd.dockerfile`](../blob/main/support/deploy/omnibus-rssd.dockerfile)</mark>. Use that as a starting point and continue to update the comments and documentation during finalization of the code.

The container will feature:
- **Dynamic Routing with Traefik**: Each RSSD will be accessible at a unique URL endpoint managed by Traefik. Only endpoints with `expose_endpoint=1` will be available as clickable links.
- **Configurable Base Path**: The Dockerfile should allow setting a custom `PROXY_BASE_PATH` at runtime to adjust endpoint paths dynamically.
- **Provenance Tracking**: The generated `provenance.tsv` file will provide traceability for the source repository, ensuring transparency.
- **User-Friendly Index Page**: The root index page will provide an overview of all available RSSDs with appropriate labels and exposure status.

Upon building and running the Docker container:
- Each RSSD will be accessible at a dedicated endpoint if exposed.
- An index page at the root URL will list all RSSDs with correct labels.
- The setup will support flexible routing and provenance tracking, suitable for deploying and debugging multiple RSSDs via a standardized containerized environment.

This setup is intended to standardize the deployment and access patterns for RSSDs using Traefik and surveilr, allowing flexible configurations and serving as a foundational setup for other environments.

The Dockerfile should be multi-staged, with each stage serving specific purposes:

1. **Stage 1 - Build Stage**
   - **Clone Git Repository**: Clone the repository `https://github.com/surveilr/www.surveilr.com.git`.
   - **Install surveilr CLI**: Use a shell script to install the surveilr CLI for processing RSSDs.
   - **Generate RSSDs**:
     - Identify and process all `package.sql.ts` files within the cloned repository to generate RSSDs (SQLite databases).
     - Each RSSD should be stored in `/rssd` with a filename format based on its relative path, replacing `/` with `-` (e.g., `/rssd/lib-pattern-example-pattern.sqlite.db`).
   - **Create Metadata Files**:
     - `index.tsv`: Tab-separated file storing metadata for each RSSD with columns:
       - `expose_endpoint`: Default `1` (exposed) or `0` (not exposed).
       - `relative_path`: Relative path of the RSSD in the repo.
       - `rssd_name`: Generated RSSD filename.
       - `port`: Unique port for each RSSD (starting from 9000).
       - `package_sql`: Full relative path to the `package.sql.ts` file.
     - `provenance.tsv`: Contains the field `git_repo` with the full URL of the cloned repository for provenance tracking.

2. **Stage 2 - Runtime Stage**
   - **Copy Artifacts**:
     - Copy RSSDs, `index.tsv`, and `provenance.tsv` from the build stage.
   - **Dynamic Traefik Configuration**:
     - Generate a `traefik.toml` file based on `index.tsv`:
       - Each RSSD with `expose_endpoint=1` should have a dedicated endpoint on a unique port, accessible via a path based on `PROXY_BASE_PATH`.
       - The root URL (`http://localhost`) should serve an `index.html` with links to each exposed RSSD endpoint.
   - **Generate `index.html`**:
     - Create a directory listing at `/rssd/index.html` that includes:
       - A title with the repository URL from `provenance.tsv`.
       - A list of all RSSDs:
         - If `expose_endpoint=1`, create a clickable `<a>` link using `package_sql` as the label.
         - If `expose_endpoint=0`, show the path with `(not exposed)` appended.
   - **SQLPage Configuration**:
     - Each RSSD endpoint should start with `SQLPAGE_SITE_PREFIX` set to its Traefik path, ensuring correct base path behavior in the web UI.

3. **Environment Variables**
   - **PROXY_BASE_PATH**: Sets the base path for all proxied endpoints. Default is `/`, but it should be customizable (e.g., `/example`).

```mermaid
flowchart LR
    subgraph Workstations
        A1[User Browser]
    end

    subgraph Container
        direction TB
        T1[Traefik]
        
        subgraph RSSD_Endpoints
            direction LR
            E1[Port 9000: surveilr web-ui<br>for Pattern 1]
            E2[Port 9001: surveilr web-ui<br>for Pattern 2]
            E3[Port 9002: surveilr web-ui<br>for Pattern 3]
            E4[Port 9003: surveilr web-ui<br>for Pattern 4]
        end

        subgraph Traefik_Config
            direction TB
            TC1["PathPrefix(/example/pattern1) -> 9000"]
            TC2["PathPrefix(/example/pattern2) -> 9001"]
            TC3["PathPrefix(/example/pattern3) -> 9002"]
            TC4["PathPrefix(/example/pattern4) -> 9003"]
        end
    end

    A1 --> |Request to eg.surveilr.com/example/pattern1| T1
    T1 --> |Proxy to Port 9000| E1
    A1 --> |Request to eg.surveilr.com/example/pattern2| T1
    T1 --> |Proxy to Port 9001| E2
    A1 --> |Request to eg.surveilr.com/example/pattern3| T1
    T1 --> |Proxy to Port 9002| E3
    A1 --> |Request to eg.surveilr.com/example/pattern4| T1
    T1 --> |Proxy to Port 9003| E4
```

**Comment by shah** [comment]
@ronikb @rinshadka @geovlazar please review the specs, finish the code and then deploy this container to `https://eg.surveilr.com`. `eg` is latin ["for example"](https://www.grammarly.com/blog/acronyms-abbreviations/i-e-vs-e-g/). 

Then, later, after [eg.surveilr.com](https://eg.surveilr.com) works manually then integrate it as a CI/CD pipeline that's run after each push.

**Comment by shah** [comment]
@rinshadka @geovlazar since we need to allow local dev sandboxes to simulate how the reverse proxy will work, please find below a Deno script that will allow you to simulate the NGINX reverse proxy so that devs can work locally on getting the SQLPage prefixes properly working before moving to a container. This script provides a simple, extensible way to test your services without requiring TLS or advanced configurations.

### Script: `reverse_proxy.ts`

```typescript
#!/usr/bin/env -S deno run --allow-net

/**
 * Simple Reverse Proxy for Local Testing
 *
 * Purpose:
 * This script acts as a lightweight HTTP reverse proxy, allowing you to test
 * services locally with simulated base URLs. It’s useful for testing service behavior
 * before setting up a full-fledged reverse proxy like NGINX.
 *
 * Usage:
 * Run this script using:
 * deno run --allow-net reverse_proxy.ts <proxyPort> <targetBaseURL>
 *
 * Example:
 * - If you want to call `http://localhost:8991/lib/pattern/my-pattern` and proxy
 *   requests to a SQLPage service running at `http://localhost:3000/lib/pattern/my-pattern`,
 *   you can run:
 *   deno run --allow-net reverse_proxy.ts 8991 http://localhost:3000
 *
 * Assumptions:
 * - The target service (e.g., SQLPage) must already be running and accessible.
 * - This proxy will forward all requests from the specified port to the target base URL.
 */

import { serve } from "https://deno.land/std@0.206.0/http/server.ts";

// Ensure required arguments are provided
if (Deno.args.length < 2) {
  console.error("Usage: deno run --allow-net reverse_proxy.ts <proxyPort> <targetBaseURL>");
  Deno.exit(1);
}

// Parse arguments: proxyPort (local listening port) and targetBaseURL
const [proxyPort, targetBaseURL] = Deno.args;

// Validate the target base URL
try {
  new URL(targetBaseURL);
} catch {
  console.error(`Invalid targetBaseURL: ${targetBaseURL}`);
  Deno.exit(1);
}

// Log the proxy setup
console.log(`Reverse proxy listening on: http://localhost:${proxyPort}`);
console.log(`Proxying requests to: ${targetBaseURL}`);

// Start the reverse proxy server
serve(async (req: Request) => {
  // Determine the full URL of the incoming request
  const incomingUrl = new URL(req.url);

  // Construct the proxied URL by replacing the origin with the target base URL
  const proxiedUrl = new URL(req.url.replace(incomingUrl.origin, targetBaseURL));

  console.log(`Proxying request: ${req.method} ${incomingUrl.href} -> ${proxiedUrl.href}`);

  try {
    // Create a proxied request with the same method, headers, and body
    const proxyRequest = new Request(proxiedUrl.toString(), {
      method: req.method,
      headers: req.headers,
      body: req.body,
    });

    // Fetch the response from the target service
    const response = await fetch(proxyRequest);

    // Add custom headers for debugging purposes
    const headers = new Headers(response.headers);
    headers.set("X-Proxy-By", "Deno Reverse Proxy");

    // Return the proxied response to the client
    return new Response(response.body, {
      status: response.status,
      headers,
    });
  } catch (error) {
    // Log and return an error response if something goes wrong
    console.error(`Error during proxying: ${error.message}`);
    return new Response("Proxy error: " + error.message, { status: 502 });
  }
}, { port: parseInt(proxyPort, 10) });
```

### Example Usage

1. **Start the SQLPage Service**
   Ensure the SQLPage service is running with the appropriate environment variable:
   ```bash
   $ SQLPAGE_SITE_PREFIX=/lib/pattern/my-pattern SQLPAGE_PORT=3000 sqlpage
   $ SQLPAGE_SITE_PREFIX=/lib/pattern/my-pattern surveilr web-ui --port 3000
   ```

   This will make the service accessible at:
   ```
   http://localhost:3000/lib/pattern/my-pattern
   ```

2. **Run the Reverse Proxy**
   Start the proxy to simulate calls to `http://localhost:8991/lib/pattern/my-pattern`:
   ```bash
   deno run --allow-net reverse_proxy.ts 8991 http://localhost:3000
   ```

3. **Test the Proxy**
   Make a request to the proxy:
   ```bash
   curl http://localhost:8991/lib/pattern/my-pattern
   ```
   The proxy will forward the request to:
   ```
   http://localhost:3000/lib/pattern/my-pattern
   ```

**Comment by rinshadka** [comment]
@shah , Team is working on automating the deployment at `https://eg.surveilr.com` via GitHub Actions CI/CD upon each push events to this repository.

**Comment by rinshadka** [comment]
Automated deployment at ```https://eg.surveilr.com``` is configured for each push events using GitHub Actions.

Ref: [Workflow](https://github.com/surveilr/www.surveilr.com/blob/main/.github/workflows/omnibus-surveilr-web-ui.yml) file.

**Comment by shah** [comment]
@rinshadka @geovlazar we need to install `sqlpkg` as part of the `eg.surveilr.com` Dockerfile build stage. In the build stage where we call `eg.surveilr.com-prepare.ts`, devs should be able to install any SQLite extension dependencies while @Lilit0x is working _static_ building of common extensions.

**Comment by rinshadka** [comment]
> [@rinshadka](https://github.com/rinshadka) [@geovlazar](https://github.com/geovlazar) we need to install `sqlpkg` as part of the `eg.surveilr.com` Dockerfile build stage. In the build stage where we call `eg.surveilr.com-prepare.ts`, devs should be able to install any SQLite extension dependencies while [@Lilit0x](https://github.com/Lilit0x) is working _static_ building of common extensions.

Modified Dockerfile: [**commit**](https://github.com/surveilr/www.surveilr.com/commit/935b69c00fe0b4b3f7414be807211aa5a8187d37#diff-c2101579146b3effc86cf43a105a28c7fc135fb3f5187d94bff067f6266b3027R23)
- Added `sqlpkg` utility installation in Docker build stage
- Configured `GITHUB_TOKEN` in the Docker build stage for authenticated GitHub API calls during `sqlpkg` installations.  
- Configured `SURVEILR_SQLPKG=$HOME/.sqlpkg` in the Docker build stage, so that `eg.surveilr.com-prepare.ts` can use this by default.
