### ISSUE TITLE
Replace all ScrewFast References

### ISSUE THREAD

**Issue by geovlazar** [surveilr/www.surveilr.com#53]
There are still many areas in www.surveilr.com where the name screwfast appears and that is not appropriate. P
lease make it a priority to ensure that all references to screwfast are changed to surveilr where appropriate and Resource Surveillance where appropriate.

**Comment by AjayKuruvath** [comment]
We have updated all ScrewFast References with surveilr.

**Comment by pradeepcdlm** [comment]
Closing this ticket as all references to ScrewFast have been updated to surveilr on the www.surveilr.com site as part of the cleanup and site quality management process.

cc @geovlazar , @AjayKuruvath , @RejinaKP
