### ISSUE TITLE
 Use Starlight's auto-generation of Sidebar from Markdown content

### ISSUE THREAD

**Issue by geovlazar** [surveilr/www.surveilr.com#57]
In surveilr.com, the docs Sidebar is improperly specified. Instead of using auto-generation features which read Markdown frontmatter you're manually generating entries, titles, etc. with is inappropriate.

Use Starlight Sidebar Autogeneration instead of making brittle manual copy/paste of the structure. Never use link for anything other than external links. Only use slugs, groups, etc

![image](https://github.com/user-attachments/assets/7a67ccd3-47d2-436c-96dd-7ad3ccb5aa8a)

As stated in the [Starlight Sidebar documentation](https://starlight.astro.build/guides/sidebar/) it's crucial to use:

1. Autogenerated groups at the highest levels and never hand-code your own unless you have to so that Markdown frontmatter from the actual `*.md` files is automatically used.
2. If you have to hand-code a group for some reason use this style so that Markdown frontmatter is automatically used.
3. If _Groups_ does not work then use `slug` so that Markdown frontmatter is automatically used.
4. Only use `link` for external pages not internal pages.

**Comment by divya-binil** [comment]
Reconfigured the sidebar menu to leverage Starlight's auto-generation feature, removing manual link and title entries for better maintainability.

![image](https://github.com/user-attachments/assets/081c5cec-0087-4450-8c5d-56070dd3cc76)

**Comment by pradeepcdlm** [comment]
Closing this ticket as the issue has been resolved with the above commit by @divya-binil.

cc @geovlazar, @AjayKuruvath
