### ISSUE TITLE
Deploy www.surveilr.com Astro repo to https://surveilr.com

### ISSUE THREAD

**Issue by pradeepcdlm** [surveilr/www.surveilr.com#7]
- [x] Initial deployment in `static` mode on GitHub Pages (`hybrid` not required)
- [x] GitHub Actions for auto deployment

**Comment by resulraveendran** [comment]
Set up GitHub Actions to automatically deploy the site to GitHub Pages and include Deno version 1.46.3 in the workflow

**Comment by shah** [comment]
We'll consider this complete for now.
