### ISSUE TITLE
Use logo contest to create branding package

### ISSUE THREAD

**Issue by ajaykumaran** [surveilr/www.surveilr.com#9]
Hi Shahid I have asked Netspective design team members to create logo options for `surveilr` as we do not have account in 99designs or others. I shall share the options that they create when I get it and then can select and iterate the best option from those.

Reference: 
1. https://99designs.com/how-it-works
2. https://99designs.com/logo-design/details

**Comment by ajaykumaran** [comment]
Hi Shahid I have asked Citrus design team members to create a logo for surveilr as we do not have account in 99designs or others. I shall share the options that they create when I get it and then can select an iterate the best option from those.

**Comment by ajaykumaran** [comment]
@shah I see that 99designs have different kind of branding packages as documented here, https://99designs.com/categories; If we just want to run contest for Logo, that also have different packages, https://99designs.com/logo-design/details; Hope you will choose the right package and load your card to get the contest started.

@ronikb please create a generalized email account for creating the purchase account in 99design and other such design contest sites.

**Comment by ronikb** [comment]
@ajaykumaran Created this DL 99design-admins@netspective.com for this purpose. use this ID to purchase it

@shah

**Comment by ajaykumaran** [comment]
[surveilr.pdf](https://github.com/user-attachments/files/17148451/surveilr.pdf)

Please find one of the logo option our internal design team created.

**Comment by shah** [comment]
That looks great @ajaykumaran let's proceed with that for now and we can close this ticket.

![Image](https://github.com/user-attachments/assets/6a818c58-7569-4b6b-879b-acee49f86d7f)

We should have another streamlined version with just the logo and `surveilr` (without "Resource Surveillance") so when there's less room we use the streamlined version. Also let's assume we're using `surveilr` lowercase so we can try some variations with that (not just uppercase).

**Comment by ajaykumaran** [comment]
Please find the three version of the above logo with `surveilr` in lowercase.

![Image](https://github.com/user-attachments/assets/b4e3e16e-f497-424b-a1fc-11bd662140c8)

![Image](https://github.com/user-attachments/assets/826d771c-adcd-4a02-aaa0-5d045ef109f2)

![Image](https://github.com/user-attachments/assets/ad78e547-069c-42b1-ae46-5de6fd53e772)

**Comment by shah** [comment]
@ajaykumaran these look nice; please replace those large images with small/medium/large to see how the logos looks in smaller sizes too. Lots of logos look great at large sizes but suffer in small.

**Comment by ajaykumaran** [comment]
@shah please find the logos in small size. 

![Image](https://github.com/user-attachments/assets/dd4aa589-6aee-4c50-8984-eb32f9df36f0)

![Image](https://github.com/user-attachments/assets/d1f55fdb-4857-4b52-9afe-8917da130d32)

![Image](https://github.com/user-attachments/assets/ddb7b1cc-9088-410f-a38e-658cda467a24)

In header without tagline would look good, but we can use the one with tagline on the landing page hero block and also in footer.

**Comment by shah** [comment]
Yes @ajaykumaran, please proceed after doing a likeness check for the logo in Google Images and other sites to make sure we're not infringing on anyone else's likeness of the "shield-like" logo.

**Comment by ajaykumaran** [comment]
@shah while checking for likeness, we saw the same type in one free stock site and the same being used by a Polish Insurance Agent company. We will make few variations to make the icon unique and share here.

**Comment by ajaykumaran** [comment]
@shah the designer provided me with three additional variations, and the one attached here seemed the best. We also checked the likeness using Google Lens, and there were no exact matches. Please review.
![surveilr-logo-without-tagline](https://github.com/user-attachments/assets/bb591db6-de77-4df5-a5bf-14e6fd12cdd9)
![surveilr-logo-with-tagline](https://github.com/user-attachments/assets/fb0d67d3-7ebb-4a8d-b733-20aeacf0d5f1)

**Comment by shah** [comment]
Excellent, let's proceed to use it and replace all our existing logos everywhere (GitHub.com, www.surveilr.com, etc.).

**Comment by shah** [comment]
@ajaykumaran as discussed with @pradeepcdlm please put brand assets into `/src/assets/brand` in multiple formats with explanations for our colors, etc. then close this ticket.
